### ISSUE TITLE
External Camera support (Apple Studio Display)

### ISSUE THREAD

**Issue by krzyzanowskim** [joshdholtz/DeckUI#12]
The camera input works for MacBook build-in camera, but doesn't work for Apple Studio Display camera (didn't check if this is the case for other external camera setup as well)

**Comment by krzyzanowskim** [comment]
ok, this is weird. Once re-attached my display, it seems to work. I blame Apple on that.

**Comment by joshdholtz** [comment]
I think this is potentially still a thing that could be improved! I have an external camera that I will attach to my MacBook so it would be nice to be able to chose which camera to use 😊 

Going to reopen this because this was also on my mind to do at some point 💪
