### ISSUE TITLE
`SlideDirection` -> `SlideTransition`

### ISSUE THREAD

**Issue by yonomitt** [joshdholtz/DeckUI#5]
In the future, it might be handy to add more transitions between slides. For instance, in Keynote, I use **Dissolve** quite often, and would miss it here. This would require adding a new case to the `SlideDirection` enum.

However, at the point of adding more transition types, the name no longer makes sense. It might be better to rename it to `SlideTransition` to more accurately reflect the functionality.

**Comment by joshdholtz** [comment]
I completely agree with this! I will get this renamed 😊
